
#person:
#  name: zhangsan
#  age: 18
#  bossFlag: true
#  bitth: 1990/1/1
#  map: {k1: v1,k2: v2}
#  list:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 狗
#    age: 2
server:
  port: 8081
spring:
  profiles:
    active: dev
---

server:
  port: 8082
  profiles: dev

---

server:
  port: 8083
  profiles: online